### ISSUE TITLE
Allow multiple hosts for ingresses

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [anycable/anycable-helm#41]
Right now it seems that only one host is possible to set, could you change it to make multiple domains possible?

**Comment by Envek** [comment]
You can use multiple hosts like this:

```yaml
ingress:
  enable: true
  path: /cable
  # 1. For automatically generated TLS certificates
  acme:
    hosts:
      - example.com
      - example.net
  # 2. For manually managed TLS certificates (or without them)
  nonAcme:
    hosts:
      - example.com
      - example.net
```
