### ISSUE TITLE
Bug and TLS-Secret gets generated, even though no TLS key provided

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [anycable/anycable-helm#47]
```yaml
className: nginx
ingress:
  enable: true
  className: nginx
  path: "/cable"
  nonAcme:
    hosts:
      - secretName: wildcard-mydomain
        names:
          - subdomain.mydomain.com

```

```shell
> helm install anycable anycable/anycable-go -n flave1a23 -f anycable.values.yaml --debug

install.go:224: 2024-10-13 16:37:10.039193 +0200 CEST m=+0.035220834 [debug] Original chart version: ""
install.go:241: 2024-10-13 16:37:10.107778 +0200 CEST m=+0.103805626 [debug] CHART PATH: /Users/myuser/Library/Caches/helm/repository/anycable-go-0.5.11.tgz

Error: INSTALLATION FAILED: template: anycable-go/templates/ingress-tls-secret.yml:3:8: executing "anycable-go/templates/ingress-tls-secret.yml" at <.tls>: can't evaluate field tls in type []interface {}
helm.go:86: 2024-10-13 16:37:10.317528 +0200 CEST m=+0.313556709 [debug] template: anycable-go/templates/ingress-tls-secret.yml:3:8: executing "anycable-go/templates/ingress-tls-secret.yml" at <.tls>: can't evaluate field tls in type []interface {}
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:158
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
	runtime/proc.go:272
runtime.goexit
	runtime/asm_arm64.s:1223
```

Any idea how to fix this?
